# Generated by Django 3.2.6 on 2021-08-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210818_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_description', models.TextField()),
                ('internship_description', models.TextField()),
                ('responsibilities', models.TextField()),
                ('qualification', models.TextField()),
                ('benefits', models.TextField()),
                ('cost', models.IntegerField()),
                ('start_date', models.TextField()),
                ('end_date', models.TextField()),
                ('contact_info', models.TextField()),
                ('feedback', models.TextField()),
            ],
        ),
    ]
