# Generated by Django 3.2.6 on 2021-08-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='contact_info2',
            field=models.TextField(null=True),
        ),
    ]
