# Generated by Django 3.2.6 on 2021-08-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_poster_contact_info2'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='company_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
